name: Docker Compose Build Latest Tag (Manual Dispatch)

# The workflow is manually triggered
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Fetch all tags and set the latest tag
      - name: Fetch tags and set the latest tag
        run: |
          git fetch --tags
          echo "LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Set up QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Prepare Docker Build
      - name: Build Docker images
        run: cp .env.example .env

      # Docker metadata for librechat-api
      - name: Docker metadata for librechat-api
        id: meta-librechat-api
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/librechat-api
          tags: |
            type=raw,value=${{ env.LATEST_TAG }},enable=true
            type=raw,value=latest,enable=true
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}

      # Build and push librechat-api
      - name: Build and push librechat-api
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.multi
          context: .
          push: true
          tags: ${{ steps.meta-librechat-api.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          target: api-build

      # Docker metadata for librechat
      - name: Docker metadata for librechat
        id: meta-librechat
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/librechat
          tags: |
            type=raw,value=${{ env.LATEST_TAG }},enable=true
            type=raw,value=latest,enable=true
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}

      # Build and push librechat
      - name: Build and push librechat
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta-librechat.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          target: node
